export const API = 'http://localhost:5001'

export const FETCH_INITIAL_DATA_REQUEST = 'FETCH_INITIAL_DATA_REQUEST'
export const FETCH_INITIAL_DATA_ERROR = 'FETCH_INITIAL_DATA_ERROR'
export const FETCH_INITIAL_DATA_SUCCESS = 'FETCH_INITIAL_DATA_SUCCESS'

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST'
export const EDIT_POST_ERROR = 'EDIT_POST_ERROR'
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'

export const EDIT_MODE = 'STATUS_UPDATE/TYPE/EDIT_MODE'
export const EDIT = 'STATUS_UPDATE/TYPE/EDIT'
export const SAVE = 'STATUS_UPDATE/TYPE/SAVE'
export const DELETE = 'STATUS_UPDATE/TYPE/DELETE'
export const CREATE = 'STATUS_UPDATE/TYPE/CREATE'
export const CANCEL = 'STATUS_UPDATE/TYPE/CANCEL'

export const REQUEST = 'STATUS_UPDATE/STATUS/REQUEST'
export const SUCCESS = 'STATUS_UPDATE/STATUS/SUCCESS'
export const ERROR = 'STATUS_UPDATE/STATUS/ERROR'

export const EDIT_POST_BEGIN = 'LOCAL_POST/EDIT_POST_BEGIN'
export const EDIT_POST_END = 'LOCAL_POST/EDIT_POST_END'
