export const API = 'http://localhost:5001'

export const FETCH_INITIAL_DATA_REQUEST = 'FETCH_INITIAL_DATA_REQUEST'
export const FETCH_INITIAL_DATA_ERROR = 'FETCH_INITIAL_DATA_ERROR'
export const FETCH_INITIAL_DATA_SUCCESS = 'FETCH_INITIAL_DATA_SUCCESS'